sonar.projectKey=majorproject-microservices
sonar.projectName=Majorproject Microservices
sonar.sources=project
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/tests/**,**/frontend/**
