apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: microservices-dev
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_USER: postgres

  ITEMS_SERVICE_URL: http://items:8000
  AUTH_SERVICE_URL: http://auth:8001
