apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
  namespace: microservices-dev
type: Opaque
stringData:
  DB_PASSWORD: postgres
  JWT_SECRET: 4c84f55165cf101ce51acf4b4c8841bdf943bc5f1916f9d5043bad99bc06b6d1
