name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Runtime
        run: echo "Setup"

      - name: Install Dependencies
        run: echo "Install"

      - name: Lint
        run: echo "Lint"

      - name: Unit Tests
        run: echo "Tests"

      - name: Build Artifact
        run: echo "Build"

      - name: Build Docker Image
        run: echo "Docker Build"

      - name: Security Scan
        run: echo "Scan"

      - name: Authenticate Cloud
        run: echo "AWS Login"

      - name: Push Image
        run: echo "Push"

      - name: Deploy
        run: echo "Deploy"

      - name: Health Check
        run: echo "Validate"

      - name: Notify
        run: echo "Notification"
