name: SSM Demo

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  create-directory:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Create Directory Through SSM
        run: |
          aws ssm send-command             --instance-ids "${{ secrets.EC2_INSTANCE_ID }}"             --document-name "AWS-RunShellScript"             --parameters commands='["mkdir -p /home/ubuntu/github-CICD","echo Directory created successfully"]'
